# Generated by Django 3.1.7 on 2021-04-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='label',
            field=models.CharField(choices=[('N', 'new'), ('G', 'good'), ('A', 'acceptable')], max_length=1),
        ),
    ]
